services:
  ghost-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="1"
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  ghost:
    image: ghost:4-alpine
    depends_on:
      - ghost-db
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__host=ghost-db
      - url=http://localhost:2368
      - database__connection__user
      - database__connection__password
      - database__connection__database
