services:
  joomla-db:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="1"
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  joomla:
    image: joomla
    restart: always
    depends_on:
      - joomla-db
    ports:
      - 80:80
    environment:
      - JOOMLA_DB_HOST=joomla-db
      - JOOMLA_DB_USER
      - JOOMLA_DB_PASSWORD
      - JOOMLA_DB_NAME
