services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    depends_on:
      - sqlserver-db
    restart: always
    ports:
      - 8080:8978
